# Generated by Django 4.2.1 on 2023-06-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_comment_reply_to_alter_photo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
